service: "redirect"

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${custom:stage, 'dev'} # dev or live
  region: eu-west-1

functions:
  redirect:
    handler: handler.redirect
    events:
      - http:
          path: /
          method: get
          cors: true

custom:
  stage: ${opt:stage, self:provider.stage}

  customDomain:
    domainName: 'redirect.ghst.co'
    basePath: ''
    stage: ${opt:stage, self:provider.stage}
    createRoute53Record: false

plugins:
  - serverless-offline
  - serverless-domain-manager
